repos:

# isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

# black
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args:
          - "--line-length=120"

# flake8
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"

# pyupgrade
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade